### ISSUE TITLE
Notify crashes when clicking on the 'About Notify' item from the menu

### ISSUE THREAD

**Issue by alexis-belmonte** [ranfdev/Notify#14]
Reporting on Notify 0.1.4 (AUR package) a bug that causes a SIGTRAP to be sent when clicking on the 'About Notify' item from the menu of the main window.

There's only this line which is relevant to our issue in `stderr`:
```
(notify:9492): Adwaita-ERROR **: 22:23:46.076: Could not parse metadata file: The resource at “/com/ranfdev/Notify/metainfo.xml” does not exist
```

I believe this is either due
- to the `data/resources/meson.build` script missing out on that metadata XML file
- to how the `PKGBUILD` script generates the list of files to package

This needs investigation -- when I have free time, I'll probably take a closer look at this unless if someone else can take care of it!

**Comment by ranfdev** [comment]
It's not related to meson, because if it were, the CI pipeline on flathub would fail to find the appstream information.

Now it's also crashing on my machine, which is weird, because it was working during development.

Tomorrow I'll try to fix it.

**Comment by topjor** [comment]
This also happens in the flatpak version.

I suspect the file location in the install to be different from what file is requested in the application but I have not looked into this.

**Comment by ranfdev** [comment]
Closed with commit https://github.com/ranfdev/Notify/commit/ee60c662d141b8dbbfafcd79403c0e2978a86f02
The metadata file is embedded in `/com/ranfdev/Notify/com.ranfdev.Notify.metainfo.xml` as described by the gresource file, but in the app I was looking for `/com/ranfdev/Notify/metainfo.xml`
