### ISSUE TITLE
Option to send notification?

### ISSUE THREAD

**Issue by RDKRACZ** [ranfdev/Notify#3]
Hello, would you consider adding the ability to send notifications to a topic?

**Comment by ranfdev** [comment]
You can send a notification by typing in the message bar and pressing enter. The next version will feature a UI to send custom messages, with a custom title, action buttons etc...

If you don't see notifications in your shell, make sure you have the latest version of Notify running. After upgrading you may need to close the previous app, which is running in background, or just reboot

**Comment by ranfdev** [comment]
If you still have problems, feel free to open another issue
