### ISSUE TITLE
Default server setting

### ISSUE THREAD

**Issue by dani3l0** [ranfdev/Notify#4]
I love the UI and the idea of native ntfy client, but entering self-hosted ntfy URL each time we subscribe the topic is exhausting...

Could you add a default server preference or at least make app remember last entered URL?

**Comment by ranfdev** [comment]
Solved in the last commit. The dialog to add a subscription will inherit the custom server from the current subscription you are viewing.
So, if you have only added subscriptions from your self-hosted ntfy server, the custom server field will always be prefilled with your self-hosted server.

**Comment by dani3l0** [comment]
Awesome! Waiting for release then
