### ISSUE TITLE
Plans to package Notify to the ArchLinux User Repository

### ISSUE THREAD

**Issue by alexis-belmonte** [ranfdev/Notify#5]
Hello!
I was wondering if there was any plan to make it available to the AUR on ArchLinux.
If not, I can do it on my own :]

**Comment by ranfdev** [comment]
I'm not going to package Notify for Arch. If you can do it, it would be great!

**Comment by alexis-belmonte** [comment]
Alright, I guess I'll do that then! Will keep you updated on it.

**Comment by alexis-belmonte** [comment]
I'll have to disable LTO during the build, otherwise [Ring won't compile](https://github.com/briansmith/ring/issues/1444) on ArchLinux. I have no idea why, but it seems that quite a lot of AUR packages do this anyway.

**Comment by alexis-belmonte** [comment]
And here we go, it works! I just need to check a few details but overall, it's done!
![image](https://github.com/ranfdev/Notify/assets/44464701/f3559ce6-da2c-456a-8169-91f06ae858ed)

**Comment by alexis-belmonte** [comment]
And there we go, available [here](https://aur.archlinux.org/packages/notify-git)! :]
