### ISSUE TITLE
Password Protected Topics

### ISSUE THREAD

**Issue by tobih7** [ranfdev/Notify#6]
Hey, I just wanted to ask if there is support planed for password protected topics?

**Comment by ranfdev** [comment]
I don't have a subscription to ntfy.sh... I have to see if the self hosted version supports authentication, so that I can test Notify against a self hosted server.

**Comment by raspbeguy** [comment]
I selfhost my ntfy, I also wish to get support for password protected topics.

**Comment by raspbeguy** [comment]
> I don't have a paid subscription to ntfy.sh... I have to see if the self hosted version supports authentication, so that I can test Notify against a self hosted server.

@ranfdev if needed I can create an account for you on my instance so you can test.

**Comment by tobih7** [comment]
@ranfdev Yes, the self-hosted version fortunately also supports password protected topics.

**Comment by ranfdev** [comment]
working on it

**Comment by ranfdev** [comment]
You can now go to the preferences page and add an account to use private topics.

The update should be available on flathub in the next few hours.
