### ISSUE TITLE
Update Cargo.toml version field to 0.1.3

### ISSUE THREAD

**Issue by alexis-belmonte** [ranfdev/Notify#9]
Will do for release 1.3

_Originally posted by @ranfdev in https://github.com/ranfdev/Notify/issues/8#issuecomment-1810657961_

The Cargo.toml file is not up to date.

**Comment by ranfdev** [comment]
Accidentally I had not pushed the v0.1.3 commit to the main branch. I had only pushed the _tag_, via `git push --tags`.

BUT the release page correctly pointed to the v0.1.3 tag, which indeed contains the commit with the Cargo.toml change.

Anyway, now I pushed everything to the main branch, sorry for the confusion. Git sometimes is confusing.
